a = 9 % 2    # 計算9%2的餘數值後，指定給變數a
print("a =", a)
c = 11        
b = c % 7    # 計算變數c除以7的餘數值後，指定給變數b 
print("b =", b)
y = 7
z = 2
result = y % z    # 將變數y, z值相除取得的餘數後，指定給變數result
print("result =", result)  
